import './globals.css';
import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';

const font = Noto_Sans({
  subsets: ['latin'], style: 'normal',
  weight: ['300', '400','500', '700']
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
